bandit src/main/python/main.py
bandit src/main/python/actions/actions.py
bandit src/main/python/dialogs/creating_url.py
bandit src/main/python/dialogs/dialogs.py
bandit src/main/python/dialogs/import_playlist.py
bandit src/main/python/dialogs/license_dialog.py
bandit src/main/python/dialogs/reset_playlist.py
bandit src/main/python/dialogs/restart_app.py
bandit src/main/python/dialogs/settings_dialog.py
bandit src/main/python/dialogs/video_info_dialog.py
bandit src/main/python/dialogs/search_results_dialog.py
bandit src/main/python/file/file.py
bandit src/main/python/menu/menu.py
bandit src/main/python/playlist/playlist.py
bandit src/main/python/playlist/video_info.py
bandit src/main/python/settings/operations.py
bandit src/main/python/settings/settings.py
bandit src/main/python/strings/check_string.py
bandit src/main/python/strings/replace_string.py
bandit src/main/python/time_and_date/convert_date.py
bandit src/main/python/time_and_date/translator.py
bandit src/main/python/translate/convert_time.py
bandit src/main/python/url/generate_url.py
bandit src/main/python/url/open_url.py
bandit src/main/python/url/url.py
