"""module settings.settings"""

APP_VERSION = "0.3.0"
APP_ICON = "icon/youtube-play.icns"
DARK_THEME_LOCATION = "theme/yt-dark-red.xml"
DEFAULT_SETTINGS_FILE_LOCATION = "config/settings_default.config"
FILE_NOT_FOUND_STRING = "File not found. No file was imported."
RECENT_FILES_STRING = "Clear recent files"
RELEASE_DATE = "June 09 2023"
SETTING_FILE_LOCATION = "config/settings.config"
WHITE_THEME_LOCATION = "theme/yt-white-red.xml"
