name: Build fbs bins

env:
  PACKAGE_NAME: youtube-playlist-generator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deb:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build deb
        shell: bash
        run: |
          sudo add-apt-repository -y ppa:brightbox/ruby-ng-experimental
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y --no-install-recommends python3-dev python3-venv pyqt6-dev libpython3.9-dev gcc-4.9 squashfs-tools fcitx-frontend-qt6 rubygems ruby2.7 ruby2.7-dev libruby2.7 ruby-xmlrpc
          sudo gem install fpm
          python3 -m venv fbs
          source fbs/bin/activate
          pip3 install pip -U
          pip3 install -r requirements/base.txt
          fbs freeze
          cp /usr/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so target/$PACKAGE_NAME/PyQt6/Qt/plugins/platforminputcontexts
          sudo chmod +x target/$PACKAGE_NAME/PyQt6/Qt/plugins/platforminputcontexts/*.so
          fbs installer

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: $PACKAGE_NAME.deb # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: target/$PACKAGE_NAME.deb
          # The desired behavior if no files are found using the provided path.

  build_dmg:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build dmg
        shell: bash
        run: |
          sudo conda create -n fbs python=3.9.5 -y -q
          eval "$(conda shell.bash hook)"
          conda activate fbs
          sudo pip3 install pip -U
          sudo pip3 install -r requirements/base.txt
          fbs freeze
          fbs installer

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: $PACKAGE_NAME.dmg # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: target/$PACKAGE_NAME.dmg
          # The desired behavior if no files are found using the provided path.

  build_exe:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.5"

      # Runs a set of commands using the runners shell
      - name: Build exe
        shell: powershell
        run: |
          pip3 install pip -U
          pip3 install -r requirements/base.txt
          fbs freeze
          fbs installer

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: $PACKAGE_NAME.exe # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: .\target\$PACKAGE_NAME.exe
          # The desired behavior if no files are found using the provided path.

  publish:
    runs-on: ubuntu-latest
    needs: [build_deb, build_dmg, build_exe]
    steps:
      - name: Download deb
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: $PACKAGE_NAME.deb # optional
          path: /tmp

      - name: Download dmg
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: $PACKAGE_NAME.dmg # optional
          path: /tmp

      - name: Download exe
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: $PACKAGE_NAME.exe # optional
          path: /tmp

      - name: Delete Artifact
        # You may pin to the exact commit or the version.
        # uses: GeekyEggo/delete-artifact@b73cb986740e466292a536d0e32e2666c56fdeb3
        uses: GeekyEggo/delete-artifact@v2.0.0
        with:
          name: |
            $PACKAGE_NAME.deb
            $PACKAGE_NAME.dmg
            $PACKAGE_NAME.exe

      - name: Generate Prerelease Release Notes
        run: |
          zip /tmp/$PACKAGE_NAME-$GITHUB_REF_NAME-setup-x64.zip /tmp/$PACKAGE_NAME.exe && rm /tmp/$PACKAGE_NAME.exe || ls /tmp
          mv /tmp/$PACKAGE_NAME.dmg /tmp/$PACKAGE_NAME-$GITHUB_REF_NAME-mac-x64.dmg
          mv /tmp/$PACKAGE_NAME.deb /tmp/$PACKAGE_NAME-$GITHUB_REF_NAME-linux.deb
          echo '# $PACKAGE_NAME `test`' >> ReleaseNotes.md

      - name: Delete Old Prerelease
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: "$GITHUB_REF_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1.11.2
        with:
          bodyFile: ReleaseNotes.md
          artifacts: "/tmp/$PACKAGE_NAME*.*"
          tag: "$GITHUB_REF_NAME"
          token: ${{ secrets.GITHUB_TOKEN }}
